site_name: ASRC Photonics Facility
site_description: Welcome to the ASRC Photonics Laboratory Shared Facility website. Here you’ll find detailed information about our available equipment, facility policies, and events.
site_url: https://asrc-photonics.github.io/Photonics-Facility
repo_name: Photonics-Facility

# Standard docs directory
docs_dir: docs


theme: 
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: orange
    - scheme: slate
      primary: deep purple
      accent: lime
  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tasklist
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      # baselevel: 2
      # separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption



plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Equipment: equipment.md
  - Howto: 
    - Become a user: become_a_user.md
  #  - Usage policies: usage_policies.md
  #  - Safety policies: safety_policies.md
  #  - Equipment usage rate: rates.md
  - Internships: 
      - Overview: internships.md
      - Anna Luo: Interns/AnnaLuo.md
  - Events: events.md
  - Python for Photonics: 
      - Overview: python/overview.md
      - Installation Guideline: python/guideline.md
      - Introduction to python: python/intro.md
      - Overview of classes: python/classes.md
      - Overview of devices: python/devices.md
      - Linear Stage: python/linear_stage.md
      - How to save and plot data: python/save_plot_data.md
      - Powermeter: python/powermeter.md
      - Knife-edge experiment: python/knife_edge.md
  - Contact: contact.md

 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/asrc-photonics
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/worldlycode/

